### ISSUE TITLE
[Task] 달력 API

### ISSUE THREAD

**Issue by sosick0418** [codestates/HABIT_TREE_Client#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 달력 api 선정 및 적용 방법 모색

### TODO
1. [x] 어떤 달력 API를 쓸 것인지 ?
2. [x] 어떻게 적용을 할 것인지?
3. [x] CSS는 어떻게 할 것인지? 정하기
### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency:  `Middle`
